import { useEffect, useState } from "react";
import { ShieldCheck } from "lucide-react";
import { motion } from "motion/react";
import { Header } from "../components/Header";
import { AnalyzePayload, InputPanel } from "../components/InputPanel";
import { Sidebar } from "../components/Sidebar";
import { useApp } from "../context/AppContext";
import { useNavigate } from "react-router";

export function GuestDashboard() {
  const { isDark, isLoggedIn } = useApp();
  const navigate = useNavigate();
  const [notice, setNotice] = useState<string | null>(null);

  useEffect(() => {
    if (isLoggedIn) navigate("/dashboard");
  }, [isLoggedIn, navigate]);

  const textPrimary = isDark ? "text-[rgba(255,255,255,0.92)]" : "text-[#0F111A]";
  const textMuted = isDark ? "text-[rgba(255,255,255,0.32)]" : "text-[#6B7280]";
  const badgeBg = isDark
    ? "border-[rgba(99,102,241,0.18)] bg-[rgba(99,102,241,0.06)] text-[rgba(165,180,252,0.8)]"
    : "border-[rgba(99,102,241,0.12)] bg-[rgba(99,102,241,0.05)] text-[#4338CA]";

  const handleAnalyze = (_payload: AnalyzePayload) => {
    setNotice("Sign in is required to run analysis.");
    navigate("/login");
  };

  return (
    <div>
      <Header variant="guest" />

      <main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6">
        <div className="flex flex-col gap-6 lg:flex-row">
          <div className="flex-1 min-w-0 space-y-6">
            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
              className="text-center lg:text-left"
            >
              <div className={`mb-4 inline-flex items-center gap-2 rounded-full border px-4 py-1.5 text-[11px] ${badgeBg}`}
                style={{ fontWeight: 500 }}>
                <ShieldCheck className="h-3 w-3" />
                Enterprise-grade AI detection
              </div>
              <h1 className={`mb-2 tracking-tight ${textPrimary}`}
                style={{ fontSize: "30px", fontWeight: 700, lineHeight: 1.2, letterSpacing: "-0.5px" }}>
                Detect AI-Generated Content
              </h1>
              <p className={`text-[13px] max-w-xl ${textMuted}`} style={{ lineHeight: "1.7" }}>
                Paste text or upload a document to analyze whether content was written by a human or generated by AI.
              </p>
            </motion.div>

            <InputPanel onAnalyze={handleAnalyze} isAnalyzing={false} errorMessage={notice} />
          </div>

          <div className="w-full lg:w-[300px] shrink-0">
            <Sidebar variant="guest" />
          </div>
        </div>
      </main>
    </div>
  );
}
