apiVersion: 1

datasources:
  - name: Google Cloud Monitoring
    uid: gcm
    type: stackdriver
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      authenticationType: gce
      defaultProject: standard-lab-493119
