import { CalendarIcon, DownloadIcon, InfoCircledIcon } from "@radix-ui/react-icons";
import { ModelLogo } from "./DesignIcons";

interface Segment { text: string; isAI: boolean; }
interface ModelAttribution { name: string; score: number; }

export interface ResultsData {
  aiScore: number;
  humanScore: number;
  confidence: number;
  label: string;
  model: string;
  submittedText?: string;
  wordCount?: number;
  submittedAt?: string;
  modelAttributions?: ModelAttribution[];
  segments?: Segment[];
  chunks: { text: string; score: number }[];
  stats: { analyzed: number; flagged: number; clean: number };
}

const previewData: ResultsData = {
  aiScore: 92,
  humanScore: 8,
  confidence: 92,
  label: "Likely AI-generated",
  model: "GPT-4",
  wordCount: 1248,
  submittedAt: "2025-05-14T10:32:00",
  modelAttributions: [
    { name: "GPT-4", score: 93 },
    { name: "Claude 3", score: 89 },
    { name: "Gemini 1.5", score: 91 },
    { name: "Llama 3", score: 86 },
  ],
  chunks: [
    { text: "RoBERTa Classifier", score: 60 },
    { text: "Stylistic Analysis", score: 20 },
    { text: "Statistical Analysis", score: 20 },
  ],
  stats: { analyzed: 36, flagged: 18, clean: 18 },
  segments: [],
};

function clampScore(score: number): number {
  return Math.max(0, Math.min(100, Math.round(score)));
}

function toneMeta(tone: "human" | "mixed" | "ai") {
  if (tone === "human") return { dot: "bg-[#2fa56d]", text: "text-[#17633f]" };
  if (tone === "mixed") return { dot: "bg-[#f6b52d]", text: "text-[#8a5200]" };
  return { dot: "bg-[#ef3a43]", text: "text-[#b32635]" };
}

function ScoreRing({ score }: { score: number }) {
  const normalized = clampScore(score);
  const angle = normalized * 3.6;

  return (
    <div
      className="relative flex h-[122px] w-[122px] shrink-0 items-center justify-center rounded-full"
      style={{ background: `conic-gradient(#f7a51c 0deg ${angle}deg, #e8edf5 ${angle}deg 360deg)` }}
      aria-label={`Confidence ${normalized}%`}
      role="img"
    >
      <div className="flex h-[94px] w-[94px] flex-col items-center justify-center rounded-full bg-white">
        <span className="text-[34px] font-bold leading-none tracking-[-0.045em] text-[#07112f]">{normalized}%</span>
      </div>
    </div>
  );
}

function MiniBars({ tone }: { tone: "human" | "mixed" | "ai" }) {
  const color = tone === "human" ? "bg-[#1263F1]" : tone === "mixed" ? "bg-[#1263F1]" : "bg-[#1263F1]";
  const heights = [12, 17, 21, 14, 28, 11, 9, 18, 13, 25, 15, 10, 20, 16, 12, 19, 14, 9, 17, 13];

  return (
    <div className="mt-4 flex h-8 items-end gap-1">
      {heights.map((height, index) => (
        <span key={index} className={`${color} w-[3px] rounded-t-[2px]`} style={{ height: `${height}px`, opacity: 0.25 + (index % 5) * 0.14 }} />
      ))}
    </div>
  );
}

export function ResultsPanel({ data, isAnalyzing = false }: { data?: ResultsData | null; isAnalyzing?: boolean }) {
  const display = data ?? previewData;
  const score = clampScore(isAnalyzing ? 32 : display.aiScore);
  const models = display.modelAttributions ?? [];
  const chunks = display.chunks?.length ? display.chunks : previewData.chunks;

  return (
        <div className="grid h-full min-h-0 overflow-hidden rounded-[14px] border border-[#a6b5cd]/70 bg-white/88 shadow-[0_22px_70px_rgba(45,67,98,0.1),inset_0_1px_0_rgba(255,255,255,0.9)] grid-rows-[238px_226px_178px_minmax(198px,1fr)]">
          <section className="min-h-0 overflow-hidden border-b border-[#d7dfed]">
            <div className="flex h-[58px] items-center justify-between border-b border-[#d7dfed] bg-[#fbfcff]/75 px-7">
              <div className="flex h-full gap-12">
                <button type="button" className="border-b-2 border-[#1263F1] px-1 text-[16px] font-semibold text-[#1263F1]">Analysis</button>
                <button type="button" className="border-b-2 border-transparent px-1 text-[16px] font-medium text-[#52627a]">Report</button>
              </div>
              <button type="button" aria-label="Download report" className="veriai-icon-button flex h-9 w-9 items-center justify-center rounded-[8px] border border-[#d7dfed] text-[#274169] hover:bg-[#eef3f9]">
                <DownloadIcon className="h-5 w-5" />
              </button>
            </div>


            <div className="grid h-[180px] grid-cols-[142px_1fr] items-center gap-5 px-7">
              <ScoreRing score={score} />
              <div className="min-w-0">
                <h2 className="flex items-center gap-3 text-[20px] font-semibold tracking-[-0.02em] text-[#ef3a43]">
                  <span className="h-3.5 w-3.5 rounded-full bg-[#ef3a43]" />
                  {display.label}
                </h2>
                <p className="mt-3 max-w-[38ch] text-[14px] font-medium leading-6 text-[#152342]">
                  Our analysis indicates that this text was likely generated by an AI model.
                </p>
                <p className="mt-4 flex items-start gap-2 text-[12px] font-medium leading-5 text-[#64748b]">
                  <InfoCircledIcon className="mt-0.5 h-4 w-4 shrink-0 text-[#7c8aa5]" />
                  <span>Probabilistic signal only. Review evidence before making an academic judgment.</span>
                </p>
              </div>
            </div>

          </section>

          <section className="grid min-h-0 grid-rows-[auto_1fr] border-b border-[#d7dfed] px-[22px] pb-[14px] pt-4">
            <div className="flex items-center justify-between pb-3">
              <h2 className="flex items-center gap-2 text-[15px] font-semibold text-[#07112f]">
                Model attribution <InfoCircledIcon className="h-4 w-4 text-[#7c8aa5]" />
              </h2>
              <span className="text-[12px] font-medium text-[#64748b]">ranked by confidence</span>
            </div>
            <div className="grid grid-cols-2 content-stretch gap-2.5">
              {models.slice(0, 4).map((model) => {
                const modelScore = clampScore(model.score);
                const scoreColor = modelScore >= 90 ? "text-[#b32635]" : "text-[#07112f]";
                return (
                  <article key={model.name} className="grid min-h-[76px] content-between rounded-[10px] border border-[#d7dfed] bg-[#f8fafc]/70 p-3">
                    <div className="flex items-center justify-between gap-3">
                      <span className="flex min-w-0 items-center gap-2 text-[14px] font-medium text-[#07112f]">
                        <ModelLogo name={model.name} className="h-6 w-6 shrink-0" />
                        <span className="truncate">{model.name}</span>
                      </span>
                      <span className={`veriai-mono text-[13px] font-semibold ${scoreColor}`}>{modelScore}%</span>
                    </div>
                    <span className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#e5ebf4]">
                      <span className="veriai-bar-fill block h-full rounded-full bg-[#1263F1]" style={{ width: `${modelScore}%` }} />
                    </span>
                  </article>
                );
              })}
            </div>
          </section>

          <section className="grid min-h-0 grid-rows-[auto_1fr] border-b border-[#d7dfed] px-[22px] pb-[14px] pt-4">
            <div className="flex items-center justify-between pb-3">
              <h2 className="flex items-center gap-2 text-[15px] font-semibold text-[#07112f]">
                Sentence-level highlights <InfoCircledIcon className="h-4 w-4 text-[#7c8aa5]" />
              </h2>
              <span className="text-[12px] font-medium text-[#64748b]">24 sentences</span>
            </div>
            <div className="grid content-stretch gap-[9px]">
              {[
                ["human", "Likely human-written", "12 sentences"],
                ["mixed", "Uncertain", "5 sentences"],
                ["ai", "Likely AI-generated", "7 sentences"],
              ].map(([toneValue, label, count]) => {
                const meta = toneMeta(toneValue as "human" | "mixed" | "ai");
                return (
                  <div key={label} className="veriai-highlight-row grid grid-cols-[18px_1fr_auto_18px] items-center gap-3 rounded-[10px] border border-[#d7dfed] bg-[#f8fafc]/70 px-3.5">
                    <span className={`h-3 w-3 rounded-full ${meta.dot}`} />
                    <span className="text-[14px] font-medium text-[#07112f]">{label}</span>
                    <span className="text-[12px] font-medium text-[#274169]">{count}</span>
                    <span className="text-[#07112f]">⌄</span>
                  </div>
                );
              })}
            </div>
          </section>

          <section className="grid min-h-0 grid-rows-[auto_1fr] px-[22px] pb-[14px] pt-4">
            <div className="flex items-center justify-between pb-3">
              <h2 className="flex items-center gap-2 text-[15px] font-semibold text-[#07112f]">
                Analysis layers <InfoCircledIcon className="h-4 w-4 text-[#7c8aa5]" />
              </h2>
              <span className="text-[12px] font-medium text-[#64748b]">signal mix</span>
            </div>
            <div className="grid min-h-0 grid-cols-3 content-stretch gap-2.5">
              {chunks.slice(0, 3).map((chunk, index) => {
                const value = clampScore(chunk.score);
                return (
                  <article key={`${chunk.text}-${index}`} className="flex min-h-0 flex-col justify-between rounded-[10px] border border-[#d7dfed] bg-[#f8fafc]/70 p-3">
                    <div className="min-w-0">
                      <h3 className="truncate text-[12px] font-semibold text-[#07112f]">{chunk.text}</h3>
                      <strong className="veriai-mono mt-2 block text-[22px] font-semibold leading-none text-[#1263F1]">{value}%</strong>
                    </div>
                    <MiniBars tone={index === 0 ? "human" : index === 1 ? "mixed" : "ai"} />
                  </article>
                );
              })}
            </div>
          </section>
        </div>
  );
}
